### ISSUE TITLE
[Bug] Pattern not working

### ISSUE THREAD

**Issue by pvillaverde** [oscarotero/netlify_cms_config#1]
Hey there! 

The pattern function for defining these restrictions on fields is not working as intended.
When creating a field like this:
```js
   t.string("twitter").hint('Usuario de Twitter, por exemplo: @AC_ODC').pattern("\@.*","Usuario de twitter"),
```
This is how it should created the config.yml file according to the [docs](https://www.netlifycms.org/docs/widgets/#common-widget-options):
```yaml
  label: "Title"
  name: "title"
  widget: "string"
  pattern: ['.{12,}', "Must have at least 12 characters"]
```
This is how it is created instead
```yaml
        pattern:
          - - '@.*'
            - Usuario de twitter
```
When loading the /admin/ page there's this error too:
```
Error loading the CMS configuration
Config Errors:

'collections[2].fields[9].pattern' must NOT have fewer than 2 items
'collections[2].fields[9].pattern[0]' must be string
'collections[2].fields[9].pattern[0]' must be a regular expression
'collections[2].fields[9].pattern[0]' must match exactly one schema in oneOf

Check your config.yml file.
```

----------------------------------------

I'm not sure how the conversion to yaml is done, but is It possible that is has to be a single  `pattern?: [string, string]` and not an array of arrays? ([file](https://github.com/oscarotero/netlify_cms_config/blob/75982df6be243df8b1d93c28a0cb9bc3e36023eb/fields/field.ts))
```ts
export interface BaseOptions {
  name?: string;
  required?: boolean;
  hint?: string;
  pattern?: [string, string][];
}

```

**Comment by oscarotero** [comment]
Good catch!
I've fixed it. Can you try it before tagging a new version? (You can import the raw file with `import t from "https://raw.githubusercontent.com/oscarotero/netlify_cms_config/main/mod.ts"`)

**Comment by pvillaverde** [comment]
![working](https://media.tenor.com/FaENh2t8h8cAAAAC/its-working-star-wars.gif)
It seems to work now! Grazas! :-) 
```yaml
            pattern:
              - '@.*'
              - Usuario de twitter
```
![imaxe](https://user-images.githubusercontent.com/31769405/205274665-b0a23717-2c85-499f-a21a-1a78889ceaa3.png)

**Comment by oscarotero** [comment]
Nice!
New version [0.3.1 released](https://github.com/oscarotero/netlify_cms_config/releases/tag/v0.3.1)

Grazas a ti!
