### ISSUE TITLE
Uncaught TypeError: field.toJson is not a function

### ISSUE THREAD

**Issue by Schotsl** [oscarotero/netlify_cms_config#2]
When I try to run this sample from the `README.md`:

```
import f from "https://deno.land/x/netlify_cms_config@v0.3.1/mod.ts";

const field = f.string("Your name");

console.log(field.toJson());
```

I get this error:

> error: Uncaught TypeError: field.toJson is not a function
> console.log(field.toJson());
>                   ^
>     at file:///usr/local/var/www/Sjors%20van%20Holst/Nicole-Trompetter-nuxt/public/config.ts:5:19

I'm running the latest version of Deno, which is v1.33.1

**Comment by oscarotero** [comment]
Sorry, there's a typo there. it's `toJSON()`
I'll fix it in a moment.
